image: codefreshplugins/docker-service
version: 0.1.0
description: Codefresh docker-service plugin
categories: []
keywords:
  - docker
  - docker-machine
  - docker-compose
sources:
  - https://github.com/codefresh-contrib/docker-service
maintainers: # (optional)
  - name: Kosta Klevensky
    email: kosta@codefresh.io
envs: []
