image: codefreshplugins/docker-service
version: 0.1.0
description: Codefresh docker-service plugin
categories:
  - Utility
keywords:
  - docker
  - docker-machine
  - docker-compose
sources:
  - https://github.com/codefresh-contrib/docker-service
maintainers: # (optional)
  - name: Kosta Klevensky
    email: kosta@codefresh.io
envs:
  - name: DOCKER_MACHINE_NAME
    type: optional
    description: Name of the created VM
